version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "7000:7000"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always 