version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:7000"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    restart: always

volumes:
  nginx_logs: 