version: '3'
services:
  build:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
    environment:
      - NODE_ENV=production

volumes:
  nginx_logs: 